const products = [
  {
    id: 1,
    imgProduct: "giay1.jpg",
    title: "Kamito TM Legend",
    description:
      "Giày cầu lông Kamito TM Legend, da High Strip PU, nhẹ, giảm chấn êm ái, đế 2 lớp cao su bám sân,bền bỉ, lót EVAGiày cầu lông Kamito TM Legend là mẫu ",
    username: "username",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "GIÀY THỂ THAO",
    likedCount: 10,
    price: "1200000đ",
  },
  {
    id: 2,
    imgProduct: "giay2.jpg",
    title: "Guyisa 1005",
    description:
      "Mũi giày sử dụng công nghệ sợi carbon nano siêu nhẹ –  Đế giày với cấu trúc đục lỗ đặc biệt làm bằng vải dệt siêu bền.",
    username: "username",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "GIÀY THỂ THAO",
    likedCount: 10,
    price: "1300000đ",
  },
  {
    id: 3,
    imgProduct: "giay3.jpg",
    title: "Guyisa 1015",
    description:
      "Giày Thể Thao Nam Mẫu Mới, Giày Sneaker Nam Tăng Chiều Cao 5cm - Phong Cách Trẻ Trung",
    username: "username",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "GIÀY THỂ THAO",
    likedCount: 10,
    price: "1300000đ",
  },
  {
    id: 4,
    imgProduct: "giay4.jpg",
    title: "Nike Air Max",
    description:
      "Giày thể thao Nike Air Max, kiểu dáng sneaker, chất liệu cao cấp, đế giày êm ái, đàn hồi tốt, thích hợp cho mọi hoạt động thể thao và hàng ngày.",
    username: "username2",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "GIÀY THỂ THAO",
    likedCount: 15,
    price: "2000000đ",
  },
  {
    id: 5,
    imgProduct: "giay5.jpg",
    title: "Adidas Superstar",
    description:
      "Giày thể thao Adidas Superstar, kiểu dáng retro, chất liệu da bền đẹp, đế giày chống trượt, thích hợp cho đi bộ và các hoạt động thể thao nhẹ nhàng.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "1500000đ",
  },
  {
    id: 6,
    imgProduct: "giay6.jpg",
    title: "Moesyayshoes",
    description:
      "Giày thể thao Adidas Superstar, kiểu dáng retro, chất liệu da bền đẹp, đế giày chống trượt, thích hợp cho đi bộ và các hoạt động thể thao nhẹ nhàng.",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "1700000đ",
  },
  {
    id: 7,
    imgProduct: "cg4.jpg",
    title: "Cao gót HMID",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: true,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1700000đ",
  },

  {
    id: 8,
    imgProduct: "cg5.jpg",
    title: "Cao gót YUS",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: false,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1700000đ",
  },
  {
    id: 9,
    imgProduct: "cg6.jpg",
    title: "Cao gót YUS",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1200000đ",
  },
  {
    id: 10,
    imgProduct: "giay10.jpg",
    title: "Accessories for Men",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "SNEAKER",
    likedCount: 20,
    price: "2100000đ",
  },
  {
    id: 11,
    imgProduct: "giay11.jpg",
    title: "Affordable fashionable winter boots",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "2200000đ",
  },
  {
    id: 12,
    imgProduct: "giay4.jpg",
    title: "Nike Air Max",
    description:
      "Giày thể thao Nike Air Max, kiểu dáng sneaker, chất liệu cao cấp, đế giày êm ái, đàn hồi tốt, thích hợp cho mọi hoạt động thể thao và hàng ngày.",
    username: "username2",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "GIÀY THỂ THAO",
    likedCount: 15,
    price: "2000000đ",
  },
  {
    id: 13,
    imgProduct: "sneaker1.jpg",
    title: "Adidas Superstar",
    description:
      "Giày thể thao Adidas Superstar, kiểu dáng retro, chất liệu da bền đẹp, đế giày chống trượt, thích hợp cho đi bộ và các hoạt động thể thao nhẹ nhàng.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "1500000đ",
  },
  {
    id: 14,
    imgProduct: "sneaker2.jpg",
    title: "Moesyayshoes",
    description:
      "Giày thể thao Adidas Superstar, kiểu dáng retro, chất liệu da bền đẹp, đế giày chống trượt, thích hợp cho đi bộ và các hoạt động thể thao nhẹ nhàng.",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "SNEAKER",
    likedCount: 20,
    price: "1700000đ",
  },
  {
    id: 15,
    imgProduct: "cg1.jpg",
    title: "Cao gót HMID",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1700000đ",
  },

  {
    id: 16,
    imgProduct: "giay11.jpg",
    title: "Cao gót YUS",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "SNEAKER",
    likedCount: 20,
    price: "1700000đ",
  },
  {
    id: 17,
    imgProduct: "sneaker3.jpg",
    title: "Van 1 Basic",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "1200000đ",
  },
  {
    id: 18,
    imgProduct: "giay13.jpg",
    title: "Accessories for Men",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "SNEAKER",
    likedCount: 20,
    price: "2100000đ",
  },
  {
    id: 19,
    imgProduct: "giay14.jpg",
    title: "Affordable fashionable winter boots.",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "2200000đ",
  },
  {
    id: 20,
    imgProduct: "cg2.jpg",
    title: "Cao gót HMID",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1700000đ",
  },

  {
    id: 21,
    imgProduct: "cg3.jpg",
    title: "Cao gót YUS",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "CAO GÓT",
    likedCount: 20,
    price: "1700000đ",
  },
  {
    id: 22,
    imgProduct: "giay12.jpg",
    title: "Best Clasic",
    description:
      "Mang lại sự sang trọng và nữ tính, giày cao gót Elegant là lựa chọn hoàn hảo cho những dịp đặc biệt. Chất liệu da tổng hợp cao cấp và thiết kế tinh tế, giày này không chỉ giúp bạn tự tin bước đi mà còn tôn lên vẻ đẹp của đôi chân.",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "1200000đ",
  },
  {
    id: 23,
    imgProduct: "giay13.jpg",
    title: "Accessories for Men",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: false,
    saved: true,
    type: "SNEAKER",
    likedCount: 20,
    price: "2100000đ",
  },
  {
    id: 24,
    imgProduct: "sneaker4.jpg",
    title: "Letter Patch Decor",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "2200000đ",
  },
  {
    id: 25,
    imgProduct: "giay14.jpg",
    title: "Affordable fashionable winter boots.",
    description:
      "Shop buy men's shoes - black, white, leather, casual shoes at ZAFUL. Find the trendy black shoes, leather shoes and casual shoes for men at affordable prices",
    username: "username3",
    avatar: "",
    isCertificated: true,
    saved: false,
    type: "SNEAKER",
    likedCount: 20,
    price: "2200000đ",
  },
];

export default products;
